### ISSUE TITLE
Gem breaks on large negatives

### ISSUE THREAD

**Issue by djrobby** [adam12/friendly_numbers#2]
See below. I think the tests should cover much larger values. Thanks!

![SS_20200416_1](https://user-images.githubusercontent.com/22199/79474189-19bf8e80-7fd4-11ea-8129-15c46389deb6.jpg)

Looks like this will do the trick (`whole` being the variable you're using):
`whole.to_s.reverse.gsub(/...(?!-)(?=.)/,'\&,').reverse`

**Comment by adam12** [comment]
Thanks for the report :+1: I'll try to ship a fix over the next few days.

**Comment by adam12** [comment]
Closed by 5e6508488c4fd03128ff7a90ee3af9aec7bbe6f1
